# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\marin\OneDrive\Documents\ITPProjetoFinal

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\marin\OneDrive\Documents\ITPProjetoFinal

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\marin\OneDrive\Documents\ITPProjetoFinal\CMakeFiles C:\Users\marin\OneDrive\Documents\ITPProjetoFinal\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\marin\OneDrive\Documents\ITPProjetoFinal\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mylib

# Build rule for target.
mylib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 mylib
.PHONY : mylib

# fast build rule for target.
mylib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/build
.PHONY : mylib/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/build
.PHONY : main/fast

funcs/apagaLinha.obj: funcs/apagaLinha.c.obj
.PHONY : funcs/apagaLinha.obj

# target to build an object file
funcs/apagaLinha.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/funcs/apagaLinha.c.obj
.PHONY : funcs/apagaLinha.c.obj

funcs/apagaLinha.i: funcs/apagaLinha.c.i
.PHONY : funcs/apagaLinha.i

# target to preprocess a source file
funcs/apagaLinha.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/funcs/apagaLinha.c.i
.PHONY : funcs/apagaLinha.c.i

funcs/apagaLinha.s: funcs/apagaLinha.c.s
.PHONY : funcs/apagaLinha.s

# target to generate assembly for a file
funcs/apagaLinha.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/funcs/apagaLinha.c.s
.PHONY : funcs/apagaLinha.c.s

funcs/apagaTabela.obj: funcs/apagaTabela.c.obj
.PHONY : funcs/apagaTabela.obj

# target to build an object file
funcs/apagaTabela.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/funcs/apagaTabela.c.obj
.PHONY : funcs/apagaTabela.c.obj

funcs/apagaTabela.i: funcs/apagaTabela.c.i
.PHONY : funcs/apagaTabela.i

# target to preprocess a source file
funcs/apagaTabela.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/funcs/apagaTabela.c.i
.PHONY : funcs/apagaTabela.c.i

funcs/apagaTabela.s: funcs/apagaTabela.c.s
.PHONY : funcs/apagaTabela.s

# target to generate assembly for a file
funcs/apagaTabela.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/funcs/apagaTabela.c.s
.PHONY : funcs/apagaTabela.c.s

funcs/criaLinha.obj: funcs/criaLinha.c.obj
.PHONY : funcs/criaLinha.obj

# target to build an object file
funcs/criaLinha.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/funcs/criaLinha.c.obj
.PHONY : funcs/criaLinha.c.obj

funcs/criaLinha.i: funcs/criaLinha.c.i
.PHONY : funcs/criaLinha.i

# target to preprocess a source file
funcs/criaLinha.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/funcs/criaLinha.c.i
.PHONY : funcs/criaLinha.c.i

funcs/criaLinha.s: funcs/criaLinha.c.s
.PHONY : funcs/criaLinha.s

# target to generate assembly for a file
funcs/criaLinha.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/funcs/criaLinha.c.s
.PHONY : funcs/criaLinha.c.s

funcs/criaTabela.obj: funcs/criaTabela.c.obj
.PHONY : funcs/criaTabela.obj

# target to build an object file
funcs/criaTabela.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/funcs/criaTabela.c.obj
.PHONY : funcs/criaTabela.c.obj

funcs/criaTabela.i: funcs/criaTabela.c.i
.PHONY : funcs/criaTabela.i

# target to preprocess a source file
funcs/criaTabela.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/funcs/criaTabela.c.i
.PHONY : funcs/criaTabela.c.i

funcs/criaTabela.s: funcs/criaTabela.c.s
.PHONY : funcs/criaTabela.s

# target to generate assembly for a file
funcs/criaTabela.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/funcs/criaTabela.c.s
.PHONY : funcs/criaTabela.c.s

funcs/listaDadosTabela.obj: funcs/listaDadosTabela.c.obj
.PHONY : funcs/listaDadosTabela.obj

# target to build an object file
funcs/listaDadosTabela.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/funcs/listaDadosTabela.c.obj
.PHONY : funcs/listaDadosTabela.c.obj

funcs/listaDadosTabela.i: funcs/listaDadosTabela.c.i
.PHONY : funcs/listaDadosTabela.i

# target to preprocess a source file
funcs/listaDadosTabela.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/funcs/listaDadosTabela.c.i
.PHONY : funcs/listaDadosTabela.c.i

funcs/listaDadosTabela.s: funcs/listaDadosTabela.c.s
.PHONY : funcs/listaDadosTabela.s

# target to generate assembly for a file
funcs/listaDadosTabela.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/funcs/listaDadosTabela.c.s
.PHONY : funcs/listaDadosTabela.c.s

funcs/listaTabelas.obj: funcs/listaTabelas.c.obj
.PHONY : funcs/listaTabelas.obj

# target to build an object file
funcs/listaTabelas.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/funcs/listaTabelas.c.obj
.PHONY : funcs/listaTabelas.c.obj

funcs/listaTabelas.i: funcs/listaTabelas.c.i
.PHONY : funcs/listaTabelas.i

# target to preprocess a source file
funcs/listaTabelas.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/funcs/listaTabelas.c.i
.PHONY : funcs/listaTabelas.c.i

funcs/listaTabelas.s: funcs/listaTabelas.c.s
.PHONY : funcs/listaTabelas.s

# target to generate assembly for a file
funcs/listaTabelas.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/funcs/listaTabelas.c.s
.PHONY : funcs/listaTabelas.c.s

funcs/pesquisaValor.obj: funcs/pesquisaValor.c.obj
.PHONY : funcs/pesquisaValor.obj

# target to build an object file
funcs/pesquisaValor.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/funcs/pesquisaValor.c.obj
.PHONY : funcs/pesquisaValor.c.obj

funcs/pesquisaValor.i: funcs/pesquisaValor.c.i
.PHONY : funcs/pesquisaValor.i

# target to preprocess a source file
funcs/pesquisaValor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/funcs/pesquisaValor.c.i
.PHONY : funcs/pesquisaValor.c.i

funcs/pesquisaValor.s: funcs/pesquisaValor.c.s
.PHONY : funcs/pesquisaValor.s

# target to generate assembly for a file
funcs/pesquisaValor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/funcs/pesquisaValor.c.s
.PHONY : funcs/pesquisaValor.c.s

utils/contaLinhas.obj: utils/contaLinhas.c.obj
.PHONY : utils/contaLinhas.obj

# target to build an object file
utils/contaLinhas.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/utils/contaLinhas.c.obj
.PHONY : utils/contaLinhas.c.obj

utils/contaLinhas.i: utils/contaLinhas.c.i
.PHONY : utils/contaLinhas.i

# target to preprocess a source file
utils/contaLinhas.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/utils/contaLinhas.c.i
.PHONY : utils/contaLinhas.c.i

utils/contaLinhas.s: utils/contaLinhas.c.s
.PHONY : utils/contaLinhas.s

# target to generate assembly for a file
utils/contaLinhas.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/utils/contaLinhas.c.s
.PHONY : utils/contaLinhas.c.s

utils/criaTabelaArquivo.obj: utils/criaTabelaArquivo.c.obj
.PHONY : utils/criaTabelaArquivo.obj

# target to build an object file
utils/criaTabelaArquivo.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/utils/criaTabelaArquivo.c.obj
.PHONY : utils/criaTabelaArquivo.c.obj

utils/criaTabelaArquivo.i: utils/criaTabelaArquivo.c.i
.PHONY : utils/criaTabelaArquivo.i

# target to preprocess a source file
utils/criaTabelaArquivo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/utils/criaTabelaArquivo.c.i
.PHONY : utils/criaTabelaArquivo.c.i

utils/criaTabelaArquivo.s: utils/criaTabelaArquivo.c.s
.PHONY : utils/criaTabelaArquivo.s

# target to generate assembly for a file
utils/criaTabelaArquivo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/utils/criaTabelaArquivo.c.s
.PHONY : utils/criaTabelaArquivo.c.s

utils/main.obj: utils/main.c.obj
.PHONY : utils/main.obj

# target to build an object file
utils/main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/utils/main.c.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/utils/main.c.obj
.PHONY : utils/main.c.obj

utils/main.i: utils/main.c.i
.PHONY : utils/main.i

# target to preprocess a source file
utils/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/utils/main.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/utils/main.c.i
.PHONY : utils/main.c.i

utils/main.s: utils/main.c.s
.PHONY : utils/main.s

# target to generate assembly for a file
utils/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/utils/main.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/utils/main.c.s
.PHONY : utils/main.c.s

utils/mostraMenu.obj: utils/mostraMenu.c.obj
.PHONY : utils/mostraMenu.obj

# target to build an object file
utils/mostraMenu.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/utils/mostraMenu.c.obj
.PHONY : utils/mostraMenu.c.obj

utils/mostraMenu.i: utils/mostraMenu.c.i
.PHONY : utils/mostraMenu.i

# target to preprocess a source file
utils/mostraMenu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/utils/mostraMenu.c.i
.PHONY : utils/mostraMenu.c.i

utils/mostraMenu.s: utils/mostraMenu.c.s
.PHONY : utils/mostraMenu.s

# target to generate assembly for a file
utils/mostraMenu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/utils/mostraMenu.c.s
.PHONY : utils/mostraMenu.c.s

utils/pagaStrlen.obj: utils/pagaStrlen.c.obj
.PHONY : utils/pagaStrlen.obj

# target to build an object file
utils/pagaStrlen.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/utils/pagaStrlen.c.obj
.PHONY : utils/pagaStrlen.c.obj

utils/pagaStrlen.i: utils/pagaStrlen.c.i
.PHONY : utils/pagaStrlen.i

# target to preprocess a source file
utils/pagaStrlen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/utils/pagaStrlen.c.i
.PHONY : utils/pagaStrlen.c.i

utils/pagaStrlen.s: utils/pagaStrlen.c.s
.PHONY : utils/pagaStrlen.s

# target to generate assembly for a file
utils/pagaStrlen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/utils/pagaStrlen.c.s
.PHONY : utils/pagaStrlen.c.s

utils/validaChavePrimaria.obj: utils/validaChavePrimaria.c.obj
.PHONY : utils/validaChavePrimaria.obj

# target to build an object file
utils/validaChavePrimaria.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/utils/validaChavePrimaria.c.obj
.PHONY : utils/validaChavePrimaria.c.obj

utils/validaChavePrimaria.i: utils/validaChavePrimaria.c.i
.PHONY : utils/validaChavePrimaria.i

# target to preprocess a source file
utils/validaChavePrimaria.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/utils/validaChavePrimaria.c.i
.PHONY : utils/validaChavePrimaria.c.i

utils/validaChavePrimaria.s: utils/validaChavePrimaria.c.s
.PHONY : utils/validaChavePrimaria.s

# target to generate assembly for a file
utils/validaChavePrimaria.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/utils/validaChavePrimaria.c.s
.PHONY : utils/validaChavePrimaria.c.s

utils/validaStringTipo.obj: utils/validaStringTipo.c.obj
.PHONY : utils/validaStringTipo.obj

# target to build an object file
utils/validaStringTipo.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/utils/validaStringTipo.c.obj
.PHONY : utils/validaStringTipo.c.obj

utils/validaStringTipo.i: utils/validaStringTipo.c.i
.PHONY : utils/validaStringTipo.i

# target to preprocess a source file
utils/validaStringTipo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/utils/validaStringTipo.c.i
.PHONY : utils/validaStringTipo.c.i

utils/validaStringTipo.s: utils/validaStringTipo.c.s
.PHONY : utils/validaStringTipo.s

# target to generate assembly for a file
utils/validaStringTipo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/utils/validaStringTipo.c.s
.PHONY : utils/validaStringTipo.c.s

utils/validaTabela.obj: utils/validaTabela.c.obj
.PHONY : utils/validaTabela.obj

# target to build an object file
utils/validaTabela.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/utils/validaTabela.c.obj
.PHONY : utils/validaTabela.c.obj

utils/validaTabela.i: utils/validaTabela.c.i
.PHONY : utils/validaTabela.i

# target to preprocess a source file
utils/validaTabela.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/utils/validaTabela.c.i
.PHONY : utils/validaTabela.c.i

utils/validaTabela.s: utils/validaTabela.c.s
.PHONY : utils/validaTabela.s

# target to generate assembly for a file
utils/validaTabela.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mylib.dir\build.make CMakeFiles/mylib.dir/utils/validaTabela.c.s
.PHONY : utils/validaTabela.c.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... main
	@echo ... mylib
	@echo ... funcs/apagaLinha.obj
	@echo ... funcs/apagaLinha.i
	@echo ... funcs/apagaLinha.s
	@echo ... funcs/apagaTabela.obj
	@echo ... funcs/apagaTabela.i
	@echo ... funcs/apagaTabela.s
	@echo ... funcs/criaLinha.obj
	@echo ... funcs/criaLinha.i
	@echo ... funcs/criaLinha.s
	@echo ... funcs/criaTabela.obj
	@echo ... funcs/criaTabela.i
	@echo ... funcs/criaTabela.s
	@echo ... funcs/listaDadosTabela.obj
	@echo ... funcs/listaDadosTabela.i
	@echo ... funcs/listaDadosTabela.s
	@echo ... funcs/listaTabelas.obj
	@echo ... funcs/listaTabelas.i
	@echo ... funcs/listaTabelas.s
	@echo ... funcs/pesquisaValor.obj
	@echo ... funcs/pesquisaValor.i
	@echo ... funcs/pesquisaValor.s
	@echo ... utils/contaLinhas.obj
	@echo ... utils/contaLinhas.i
	@echo ... utils/contaLinhas.s
	@echo ... utils/criaTabelaArquivo.obj
	@echo ... utils/criaTabelaArquivo.i
	@echo ... utils/criaTabelaArquivo.s
	@echo ... utils/main.obj
	@echo ... utils/main.i
	@echo ... utils/main.s
	@echo ... utils/mostraMenu.obj
	@echo ... utils/mostraMenu.i
	@echo ... utils/mostraMenu.s
	@echo ... utils/pagaStrlen.obj
	@echo ... utils/pagaStrlen.i
	@echo ... utils/pagaStrlen.s
	@echo ... utils/validaChavePrimaria.obj
	@echo ... utils/validaChavePrimaria.i
	@echo ... utils/validaChavePrimaria.s
	@echo ... utils/validaStringTipo.obj
	@echo ... utils/validaStringTipo.i
	@echo ... utils/validaStringTipo.s
	@echo ... utils/validaTabela.obj
	@echo ... utils/validaTabela.i
	@echo ... utils/validaTabela.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

